#!/bin/bash

#converts all ipython notebooks to latex


FILES="*.md"

for f in $FILES
do
    echo "opening $f"
    python acrofinder.py "$f" > tmp.tex
    rm "$f"
    mv tmp.tex $f
    printf "finished moving \n\n"
done

echo " <<<<<<<<<<<<< finished >>>>>>>>>>>>>>>>>>>>>>>>>>"

#pdflatex notebooks.tex

#rm *.log *.aux
